### PR TITLE
Remove yarn dependency

### PR DESCRIPTION
**Pull request by markwylde**
Would you be strongly against moving back to npm?

### CODE REVIEW

**Comment by adamansky** [comment]
Hi Mark! Personally I prefer yarn for many reasons and don't want to loose it in this project. I'm not against to keep yarn and npm together is it is possible =)

**Comment by markwylde** [comment]
Fair enough Adam. It was worth a shot :p

Yeah, I think I might be able to "auto detect" if yarn is installed.

Would you be happy for the following logic:
1) If `yarn` is found on the system,then it will be used
2) If `yarn` is not found, then it will fall back to npm

If so, I'll have a look.

**Comment by markwylde** [comment]
Gonna give up on this one Adam. My idea was to try and reduce the "dependencies" needed to install ejdb, using `node-gyp` to make it as easy to install as sqlite.

But I just don't have a solid enough knowledge of `c`, `c++`, building, make, etc.

**Comment by erfanium** [comment]
NPM is the only official package manager for node. I don't want to use yarn and this yarn dependency is very annoying.

**Comment by markwylde** [comment]
@erfanium I have a fork that only includes the stuff needed for node, with no typescript or yarn:

https://github.com/markwylde/node-ejdb-lite

**Pull request closed without merging**
